tls_protocols:
  - TLSv1.2

enable_ciphers:
  - DHE-RSA-AES128-GCM-SHA256
  - ECDHE-RSA-AES128-GCM-SHA256
  - DHE-RSA-AES256-GCM-SHA384
  - ECDHE-RSA-AES256-GCM-SHA384

disable_ciphers:
  - ECDHE-ECDSA-AES128-GCM-SHA256
  - ECDHE-ECDSA-AES256-GCM-SHA384
  - ECDHE-ECDSA-AES128-SHA256
  - ECDHE-ECDSA-AES256-SHA384
  - ECDHE-RSA-AES128-GCM-SHA256
  - ECDHE-RSA-AES256-GCM-SHA384
  - ECDHE-RSA-AES128-SHA256
  - ECDHE-RSA-AES256-SHA384
  - DHE-RSA-AES128-GCM-SHA256
