---
mspassword:
    - ms_password
msusername:
    - ms_username
ldappassword:
    - ldap_password
nexususername:
    - analytics_nexus_username
nexuspassword:
    - analytics_nexus_password
offboardingnexuspassword:
    - offboard_nexus_password
apiportalclientid:
    - api_portal_clientID
apiportalclientsecret:
    - api_portal_clientSecret
hanaclientsecret:
    - hana_clientSecret
hanaclientid:
    - hana_clientID
dynatraceapitoken:
    - dynatrace_api_token
ansible_ssh_user:
    - analytic_agent_ssh_user_name
pgpassword:
    - pg_password